name: My-application-CI

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      image_version:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ${{ inputs.runner }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USER }}/mynode-app:${{ inputs.image_version }}
        
    - name: printing current image
      run: |
        echo "### Image build & version" >> $GITHUB_STEP_SUMMARY
        echo "|                                                   Docker_Image_Built                                                  |" >> $GITHUB_STEP_SUMMARY
        echo "|-----------------------------------------------------------------------------------------------------------------------|" >> $GITHUB_STEP_SUMMARY
        echo "|    mynode-app:${{ inputs.image_version }}  |" >> $GITHUB_STEP_SUMMARY
